// Stub — contract macros for crates.io builds.
// Full version generated by: pv codegen contracts/ -o src/generated_contracts.rs
macro_rules! contract_pre_configuration {
    () => {{}};
    ($i:expr) => {{
        let _ = &$i;
    }};
}
